std = "lua51"
max_line_length = false

globals = {
    "C_ChatInfo",
    "ChatEdit_InsertLink",
    "ChatFrame_AddMessageEventFilter",
    "ChatFrame_OpenChat",
    "ClearCursor",
    "CreateFrame",
    "CreateMacro",
    "DEFAULT_CHAT_FRAME",
    "DeleteMacro",
    "EditMacro",
    "ElvUI",
    "GameTooltip",
    "GetActionInfo",
    "GetMacroIndexByName",
    "GetMacroInfo",
    "GetNumMacros",
    "GetScreenHeight",
    "GetScreenWidth",
    "GetServerTime",
    "HideUIPanel",
    "hooksecurefunc",
    "InCombatLockdown",
    "ItemRefTooltip",
    "MacroFrame",
    "MacroSetsTheme",
    "MacroSetsBackup",
    "MacroSetsDB",
    "MacroSetsFunctions",
    "MAX_ACCOUNT_MACROS",
    "MAX_CHARACTER_MACROS",
    "PickupMacro",
    "PlaceAction",
    "RegisterAddonMessagePrefix",
    "Settings",
    "SettingsPanel",
    "SendAddonMessage",
    "SetItemRef",
    "ShowUIPanel",
    "SlashCmdList",
    "SLASH_MACROSETS1",
    "Tukui",
    "UIParent",
    "UISpecialFrames",
    "importExportEditBox",
    "macroSetsCategory",
    "macroSetsOptionsPanel",
    "print",
    "strsplit",
    "time",
}

ignore = {
    "211", -- unused local variable
    "212", -- unused argument
    "213", -- unused loop variable
}
