name: Create Release Zip

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Zip Utility
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Determine Tag Name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Create Release Zip File
        id: create_zip
        run: |
          zip_name="MacroSets-${{ steps.tag_name.outputs.TAG_NAME }}.zip"
          echo "ZIP_NAME=$zip_name" >> "$GITHUB_OUTPUT"
          zip -r $zip_name . -x '*.git*'
