name: Create Release Zip

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Zip Utility
        run: sudo apt-get install zip

      - name: Determine Tag Name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Create Release Zip File
        run: |
          zip_name="MacroSets-${{ steps.tag_name.outputs.TAG_NAME }}.zip"
          echo "::set-output name=ZIP_NAME::$zip_name"
          zip -r $zip_name . -x '*.git*'
